### ISSUE TITLE
AppImage does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [oamldev/oamlStudio#2]
AppImage does not run on Ubuntu 14.04,

```
AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-7041/AppRun)
```

For the solution please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6.

Ubuntu 14.04 is currently the oldest still-supported LTS release, so it would be great if you could support it.

Reference:
https://github.com/AppImage/appimage.github.io/pull/457

**Comment by marcelofg55** [comment]
Thanks for the report, I'll try to get it working with Ubuntu 14.04. Also thanks for your work on AppImage :).

**Comment by marcelofg55** [comment]
I've just published a new version that should work on Ubuntu 14.04.
https://github.com/oamldev/oamlStudio/releases/tag/v1.1.1

**Comment by probonopd** [comment]
Thank you. For some reason, it looks like it does not paint a window on the screen in our automated test, but that may be an unrelated issue (possibly in AppImageHub), hence closing here.

Thanks!

**Comment by marcelofg55** [comment]
You're welcome! That's weird, maybe it could be related to wxWidgets?
