### ISSUE TITLE
oamlStudio.exe - System Error

### ISSUE THREAD

**Issue by NoodleSushi** [oamldev/oamlStudio#4]
Already re-downloaded oamlStudio-v1.1.1-Win.zip and re-opened multiple times yet this error still appears
![capture](https://user-images.githubusercontent.com/34954180/39284162-86fbe9b2-4944-11e8-9e87-0bd906c8c9e1.PNG)

**Comment by marcelofg55** [comment]
Seems I forgot the archive.dll file in the zip, here you go:
[archive.zip](https://github.com/oamldev/oamlStudio/files/1951871/archive.zip)

**Comment by NoodleSushi** [comment]
omg it works thank you @marcelofg55, I might make tutorials for this sooner or later

**Comment by marcelofg55** [comment]
Some tutorials would be awesome! If you need any help let me know :D
